package component

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"
)

// TODO: move to a separate util and replace all the gql queries with this
// wrapper for gql query
func wrapQuery(query string) string {
	return `{"query": "` + query + `"}`
}

func sanitizeString(input string) string {
	reg, _ := regexp.Compile("[^a-zA-Z0-9]+")
	processedString := reg.ReplaceAllString(strings.ToLower(strings.TrimSpace(input)), "-")
	return processedString
}

func GetComponentQuery(componentHandler string, projectId string) string {
	return wrapQuery(fmt.Sprintf(`
		query Component {
			component(
				componentHandler: \"%s\"
				projectId: \"%s\" 
			) {
				name
				version
				description
				handler
				orgHandler
				projectId
				displayName
				displayType
				createdAt
				id
				repository {
					bitbucketServerUrl
					serverUrl
					gitProvider
					nameApp
					nameConfig
					branch
					branchApp
					organizationApp
					organizationConfig
					isUserManage
					appSubPath
					repoCredRef
					byocBuildConfig {
						id
						isMainContainer
						containerId
						componentId
						repositoryId
						dockerContext
						dockerfilePath
						oasFilePath
					}
					buildpackConfig {
						versionId,
						buildContext,
						languageVersion,
						buildpack {
							id,
							language
						}
					}
					byocWebAppBuildConfig {
						id
						containerId
						componentId
						repositoryId
						dockerContext
						webAppType
						buildCommand
						packageManagerVersion
						outputDirectory
					}
				}
				project {
					id
					orgId
					name
					version
					createdDate
					handler
					region
					description
					repository
					branch
					gitProvider
					gitOrganization
				}
				apiVersions {
					id
					apiVersion
					latest
                    versionId
					appEnvVersions {
						environmentId
						releaseId
					}
				}
				deploymentTracks {
					id
					createdAt
					updatedAt
					apiVersion
					branch
					description
					componentId
					latest
					versionStrategy
				}		
			}
		}
	`,
		componentHandler,
		projectId))
}

func GetComponentRepoQuery(componentHandler string, projectId string) string {
	return wrapQuery(fmt.Sprintf(`
		query Component {
			component(
				componentHandler: \"%s\"
				projectId: \"%s\" 
			) {
				name
				version
				description
				handler
				orgHandler
				projectId
				displayName
				displayType
				createdAt
				id
				repository {
					bitbucketServerUrl
					serverUrl
					gitProvider
					nameApp
					nameConfig
					branch
					branchApp
					organizationApp
					organizationConfig
					isUserManage
					appSubPath
				}
				apiVersions {
					id
					apiVersion
					latest
                    versionId
					appEnvVersions {
						environmentId
						releaseId
					}
				}
				deploymentTracks {
					id
					createdAt
					updatedAt
					apiVersion
					branch
					description
					componentId
					latest
					versionStrategy
				}	
			}
		}
	`,
		componentHandler,
		projectId))
}

func GetGenerateEndpointsQuery(componentId string, versionId string, releaseId string, commitHash string) string {
	return wrapQuery(fmt.Sprintf(`
		mutation GenerateEndpoints {
			generateComponentEndpoints(
				input: {
					componentId: \"%s\"
					versionId: \"%s\"
					releaseId: \"%s\"
					commitHash: \"%s\"
				}
			) {
				id
				createdAt
				updatedAt
				releaseId
				port
				environmentId
				displayName
				invokeUrl
				hostName
				isAutoGenerated
				protocol
				apiContext
				apiDefinitionPath
				visibility
				type
				apimId
				apimRevisionId
				apimName
				projectUrl
				organizationUrl
				publicUrl
				state
				stateReason {
					code
					message
					details
					workerId
				}
				isDeleted
				deletedAt
			}
		}
	`,
		componentId,
		versionId,
		releaseId,
		commitHash,
	))
}

func GetProjectComponentsQuery(orgHandle string, projectId string) string {
	return wrapQuery(fmt.Sprintf(`query {components(orgHandler: \"%s\", projectId: \"%s\") {projectId, id, description, name, handler, displayName, displayType, version, createdAt, lastBuildDate, orgHandler, apiVersions { apiVersion, proxyName, proxyUrl, proxyId, id, state, latest, branch, accessibility}, deploymentTracks{id, createdAt, updatedAt, apiVersion, branch, description, componentId, latest, versionStrategy}, isSystemComponent}} `,
		orgHandle, projectId))
}

func GetProjectComponentsWithSystemQuery(orgHandle string, projectId string) string {
	return wrapQuery(fmt.Sprintf(`query {components(orgHandler: \"%s\", projectId: \"%s\", options: { filter: { withSystemComponents: true }}) {projectId, id, description, name, handler, displayName, displayType, componentSubType, version, createdAt, lastBuildDate, orgHandler, apiVersions { apiVersion, proxyName, proxyUrl, proxyId, id, state, latest, branch, accessibility}, deploymentTracks{id, createdAt, updatedAt, apiVersion, branch, description, componentId, latest, versionStrategy}, isSystemComponent}} `,
		orgHandle, projectId))
}

func GetCreateByoiComponentQuery(
	name string,
	displayName string,
	description string,
	projectId string,
	componentType string,
	imageUrl string,
	registryId string,
	version string,
	isSystemComponent string,
) string {
	return wrapQuery(
		fmt.Sprintf(`mutation{ createByoiComponent( component: { name: \"%s\", displayName: \"%s\", description: \"%s\", projectId: \"%s\", componentType: \"%s\", metadata: { version: \"%s\", labels: \"\", isSystemComponent: \"%s\" }, port: null, imageUrl: \"%s\", registryId: \"%s\" }){ id }} `,
			sanitizeString(name),
			displayName,
			description,
			projectId,
			componentType,
			version,
			isSystemComponent,
			imageUrl,
			registryId,
		))
}

func GetDeployImageQuery(
	componentId string,
	releaseId string,
	imageUrl string,
) string {
	return wrapQuery(
		fmt.Sprintf(`
			mutation {
				deployImage(
					input: {
					componentId: \"%s\",
					releaseId:\"%s\",
					imageUrl: \"%s\",
					imageId:  \"\",
					cron: \"\",
					cronTimezone: \"\",
					}
				) {
					message
					success
				}
				}`,
			componentId,
			releaseId,
			imageUrl,
		))
}

func getSrcGitRepoUrl(gitOrgName string, gitRepoName string) string {
	baseUrl := "https://github.com"

	return fmt.Sprintf(`%s/%s/%s`,
		baseUrl,
		gitOrgName,
		gitRepoName,
	)
}

func GetComponentDeploymentQuery(orgHandler string, orgUuid string, componentId string, versionId string, environmentId string) string {
	return wrapQuery(
		fmt.Sprintf(`query { componentDeployment(orgHandler: \"%s\", orgUuid:\"%s\", componentId:\"%s\",versionId:\"%s\",environmentId:\"%s\",) {
			environmentId
			configCount
			apiId
			releaseId
			apiRevision {
				id
				displayName
			}
			build{
				buildId
				deployedAt
				commit {
					author {
						name
						date
						email
						avatarUrl
					}
					sha
					message
					isLatest
				}
                runId
			}
			imageUrl
			invokeUrl
			versionId
			deploymentStatus
			deploymentStatusV2
			version
			cron
			cronTimezone
			}
		}`,
			orgHandler,
			orgUuid,
			componentId,
			versionId,
			environmentId,
		))
}

func GetComponentDeployQuery(componentId string, versionId string, envId string, branch string, sha string, shaDate string) string {
	return wrapQuery(fmt.Sprintf(`
		mutation {
			deployComponent(
				deployment: {
					componentId: \"%s\",
					versionId: \"%s\",
					envId: \"%s\",
					branch: \"%s\",
					sha: \"%s\",
					cron: \"\",
					cronTimezone: \"\",
					shaDate: \"%s\",
				}
			) {
				message
				success
			}
		}
	`,
		componentId,
		versionId,
		envId,
		branch,
		sha,
		shaDate,
	))
}

func GetDeploymentStatusByVersionQuery(componentId string, versionId string) string {
	return wrapQuery(fmt.Sprintf(`
		query {
			deploymentStatusByVersion(
				versionId: \"%s\",
				componentId: \"%s\"
			){
				id
				sha
				completed_at
				started_at
				name
				status
				conclusion
				isAutoDeploy
				failureReason
				sourceCommitId
				buildRef
				clusterId
			}
		}
	`, versionId, componentId))
}

func GetDeploymentTrackImagesQuery(componentId string, versionId string) string {
	return wrapQuery(fmt.Sprintf(`
		query {
            deploymentTrackImages(
                input: {
                    componentId: \"%s\",      
                    id: \"%s\"
                }
            ) {        
                imageId
                commitHash
                commitMessage
                createdAt
                updatedAt
            }    
        } 
	`, componentId, versionId))
}

func GetDisableAutoBuildQuery(componentId string, versionId string, envId string) string {
	return wrapQuery(
		fmt.Sprintf(`mutation { 
			handleDisableAutoBuild(
				componentId:\"%s\",
				versionId: \"%s\",
				envId: \"%s\"
			){
				success
				message
			}
		}`,
			componentId,
			versionId,
			envId,
		))
}

func GetEnableAutoBuildQuery(componentId string, versionId string, envId string) string {
	return wrapQuery(fmt.Sprintf(`
		mutation { 
			handleEnableAutoBuild(
				componentId:\"%s\",
				versionId: \"%s\",
				envId: \"%s\"
			){
				success
				message
			}
		}
	`,
		componentId,
		versionId,
		envId,
	))
}

func GetDeleteComponentQuery(orgHandler, cmpId, projectId string) string {
	return wrapQuery(fmt.Sprintf(`
		mutation{ 
			deleteComponentV2(
				orgHandler: \"%s\", 
				componentId: \"%s\", 
				projectId: \"%s\"
			) {
				status, canDelete, message, encodedData
			}
		}`,
		orgHandler,
		cmpId,
		projectId,
	))
}

func GetRepoMetadataQuery(gitOrgName, gitRepoName, branchName, subpath, secretRef string) string {
	return wrapQuery(fmt.Sprintf(`query {
		repoMetadata (organizationName:  \"%s\", repoName: \"%s\", branch: \"%s\", subPath: \"%s\", buildpackId: \"\", dockerFilePath: \"\",dockerContextPath: \"\",openAPIPath: \"\",componentId: \"\", testRunnerType: \"\",secretRef: \"%s\",isService: false,isPublicRepo: false) {
			 isBareRepo,
			 isSubPathEmpty
			 isSubPathValid
			 isValidRepo
			 hasBallerinaTomlInPath
			 hasBallerinaTomlInRoot
			 isDockerfilePathValid
			 hasDockerfileInPath
			 isDockerContextPathValid
			 isOpenApiFilePathValid
			 hasOpenApiFileInPath
			 hasPomXmlInPath
			 hasPomXmlInRoot
		}
	}`,
		gitOrgName,
		gitRepoName,
		branchName,
		subpath,
		secretRef))
}

func GetGitTokenForRepositoryQuery(gitOrg, gitRepo, secretRef string) string {
	return wrapQuery(fmt.Sprintf(`query {
			gitTokenForRepository(
				req: {
					gitOrg: \"%s\",
					gitRepo: \"%s\"
					}
				) {
					token
					gitOrganization
					gitRepository
				}
			}`,
		gitOrg,
		gitRepo))
}

func GetBuildLogsForType(componentId string, runId int, logType string) string {
	runIdStr := strconv.Itoa(runId)
	return wrapQuery(fmt.Sprintf(`query {
		buildLogs (componentId:  \"%s\", runId: \"%s\") {
			%s
		}
	}`,
		componentId,
		runIdStr,
		logType))
}

func GetAutoBuildTriggerStatusQuery(componentId string, versionId string) string {
	return wrapQuery(fmt.Sprintf(`
		query {
			autoBuildTrigger(
				componentId: \"%s\",
				versionId: \"%s\"       
			){
				success,
				data {
					autoBuildId, 
					autoBuildEnabled, 
					componentId, 
					versionId,
					envId
				},
				message
			}
		}
	`, componentId, versionId))
}

func (c *GraphQLClient) getUpdateCodeServerQuery(
	userId string,
	organizationId string,
	projectId string,
	componentId string,
	orgHandle string,
	imageUrl string,
	registryId string,
	sourceCommitHash string,
) (string, error) {

	query := fmt.Sprintf(`mutation{ updateCodeServer(
      input: {
        userId: \"%s\",
        organizationId: \"%s\",    
        projectId: \"%s\",
        componentId: \"%s\",
        orgHandle:\"%s\",
        imageUrl: \"%s\",
        registryId: \"%s\",
        sourceCommitHash: \"%s\"
      })}`, userId, organizationId, projectId, componentId, orgHandle, imageUrl, registryId, sourceCommitHash)

	return wrapQuery(query), nil
}
