package project

import "time"

type ProjectEnvironment struct {
	Name         string   `json:"name"`
	ID           string   `json:"id"`
	Env          string   `json:"choreoEnv"`
	VHost        string   `json:"vhost"`
	APIEnvName   string   `json:"apiEnvName"`
	IsMigrating  bool     `json:"isMigrating"`
	APIMEnvID    string   `json:"apimEnvId"`
	Namespace    string   `json:"namespace"`
	SandboxVHost string   `json:"sandboxVhost"`
	Critical     bool     `json:"critical"`
	IsPDP        bool     `json:"isPdp"`
	PromoteFrom  []string `json:"promoteFrom"`
	DPID         string   `json:"dpId"`
	TemplateId   string   `json:"templateId"`
}

type EndpointStateReason struct {
	Code     string `json:"code"`
	Message  string `json:"message"`
	Details  string `json:"details"`
	WorkerID string `json:"workerId"`
}

type Endpoint struct {
	ID                  string              `json:"id"`
	CreatedAt           time.Time           `json:"createdAt"`
	UpdatedAt           time.Time           `json:"updatedAt"`
	ReleaseID           string              `json:"releaseId"`
	EnvironmentID       string              `json:"environmentId"`
	DisplayName         string              `json:"displayName"`
	Port                int                 `json:"port"`
	Type                string              `json:"type"`
	APIContext          string              `json:"apiContext"`
	APIDefinitionPath   string              `json:"apiDefinitionPath"`
	InvokeURL           string              `json:"invokeUrl"`
	Visibility          string              `json:"visibility"`
	NetworkVisibilities []string            `json:"networkVisibilities"`
	HostName            string              `json:"hostName"`
	IsAutoGenerated     bool                `json:"isAutoGenerated"`
	APIMID              string              `json:"apimId"`
	APIMRevisionID      string              `json:"apimRevisionId"`
	APIMName            string              `json:"apimName"`
	ProjectURL          string              `json:"projectUrl"`
	OrganizationURL     string              `json:"organizationUrl"`
	PublicURL           string              `json:"publicUrl"`
	State               string              `json:"state"`
	StateReason         EndpointStateReason `json:"stateReason"`
	IsDeleted           bool                `json:"isDeleted"`
	DeletedAt           time.Time           `json:"deletedAt"`
}

type DeleteProjectResponse struct {
	Status  string `json:"status"`
	Details string `json:"details"`
}

type EnviroumentListResponse struct {
	ListEnvironments []EnvMetadata `json:"listEnvironments"`
}

type EnvMetadata struct {
	ExternalEnvID string `json:"externalEnvId"`
	ID            string `json:"id"`
	InternalEnvID string `json:"internalEnvId"`
	SandboxEnvID  string `json:"sandboxEnvId"`
	Name          string `json:"name"`
	Region        string `json:"region"`
	Type          string `json:"type"`
	Typename      string `json:"__typename"`
}
