package project

import "fmt"

// wrapper for gql query
func wrapQuery(query string) string {
	return `{"query": "` + query + `"}`
}

// Get Projects by Org ID
func GetProjectsByOrgIDQuery(orgID string) string {
	return wrapQuery(`query { projects(orgId: ` +
		orgID +
		`) { id, orgId, name, version, createdDate, handler, region, description, repository, branch, gitProvider, gitOrganization } }`)
}

func GetProjectEnvironmentsQuery(orgUuid string, projectId string) string {
	query := fmt.Sprintf(`query { environments(orgUuid:\"%s\", projectId:\"%s\"){ name, id, choreoEnv, vhost, apiEnvName, isMigrating, apimEnvId, namespace, sandboxVhost, critical, isPdp, promoteFrom, dpId, templateId } }`,
		orgUuid,
		projectId,
	)
	return wrapQuery(query)
}

func GetComponentEndpointsQuery(componentId string, versionId string) string {
	query := fmt.Sprintf(`query List {
		componentEndpoints(
		  input: {
			componentId: \"%s\"
			versionId: \"%s\"
		  }
		) {
		  id
		  createdAt
		  updatedAt
		  releaseId
		  environmentId
		  displayName
		  port
		  type
		  apiContext
		  apiDefinitionPath
		  invokeUrl
		  visibility
		  networkVisibilities
		  hostName
		  isAutoGenerated
		  apimId
		  apimRevisionId
		  apimName
		  projectUrl
		  organizationUrl
		  publicUrl
		  state
		  stateReason {
			code
			message
			details
			workerId
		  }
		  isDeleted
		  deletedAt
		}
	  }`,
		componentId,
		versionId,
	)
	return wrapQuery(query)
}

func GetProjectInfoQuery(orgId string, projectId string) string {
	query := fmt.Sprintf(`
		query {
			project(orgId: %s, projectId: \"%s\") {
				handler
				region
				deploymentPipelineId
				extendedHandler
				version
				labels
				orgId
				id
				owner
				description
				createdDate
				repository
				gitOrganization
				branch
				type
				secretRef
				gitProvider
				name
			}
		}
		`,
		orgId,
		projectId,
	)
	return wrapQuery(query)
}

func GetProjectComponentsQuery(orgId string, orgHandle string, projectId string) string {
	return wrapQuery(fmt.Sprintf(`
		query Project {
			project(orgId: %s, projectId: \"%s\") {
				components(orgHandler: \"%s\") {
					name
					status
					version
					labels
					description
					ownerName
					orgId
					orgUuid
					handler
					orgHandler
					canDelete
					createStatus
					projectId
					apiId
					deleteReason
					displayName
					displayType
					createdAt
					lastBuildDate
					updatedAt
					id
					httpBased
					initStatus
					isMigrationCompleted
					skipDeploy
					isUnifiedConfigMapping
				}
			}
		}
	`, orgId, projectId, orgHandle))
}

func GetDeleteProjectQuery(orgId string, projectId string) string {
	return wrapQuery(fmt.Sprintf(`
		mutation{ 
			deleteProject(orgId: %s, projectId: \"%s\"){
				status,
				details 
			} 
		}
	`, orgId, projectId))
}

func FetchEnvironmentsQuery(orgId, projectId string) string {
	return fmt.Sprintf(`{
        "operationName": "environments",
        "variables": {
            "org": {
                "orgId": "%s"
            },
            "projectId": "%s"
        },
        "query": "query environments($org: OrgFilter!, $projectId: String) {\n  listEnvironments(org: $org, projectId: $projectId) {\n    externalEnvId\n    id\n    internalEnvId\n    sandboxEnvId\n    name\n    region\n    type\n    __typename\n  }\n}\n"
    }`, orgId, projectId)
}
