package testuser

import "github.com/mark3labs/mcp-go/mcp"

var ManageTestUsersTool = mcp.NewTool("manage_test_users",
	mcp.WithTitleAnnotation("Manage Test Users"),
	mcp.WithDescription("Manages test users within a specific environment. Required when web apps are deployed with managed auth enabled. This tool allows you to add new test users or list existing ones. If 'action' is 'add', 'username', 'password', and 'email' are required, along with optional 'first_name', 'last_name', and 'groups'. If 'action' is 'list', no additional parameters are required."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(false),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("action",
		mcp.Required(),
		mcp.Description("The operation to perform. Always first use 'list' to check if the test user is already created."),
		mcp.Enum(
			"list",
			"add",
		),
	),
	mcp.WithString("environment_template_id",
		mcp.Required(),
		mcp.Description("The template ID of the environment where test users are managed."),
	),
	mcp.WithString("username",
		mcp.Description("Required if 'action' is 'add'. The username for the new test user."),
	),
	mcp.WithString("password",
		mcp.Description("Required if 'action' is 'add'. The password for the new test user."),
	),
	mcp.WithString("email",
		mcp.Description("Required if 'action' is 'add'. The email address for the new test user."),
	),
	mcp.WithString("first_name",
		mcp.Description("The first name of the test user, if 'action' is 'add'."),
	),
	mcp.WithString("last_name",
		mcp.Description("The last name of the test user, if 'action' is 'add'."),
	),
	mcp.WithString("groups",
		mcp.Description("A comma-separated list of groups for the test user, if 'action' is 'add'."),
	),
)
