package configurations

import "github.com/mark3labs/mcp-go/mcp"

var CreateConfigurationsTool = mcp.NewTool("create_configurations",
	mcp.WithTitleAnnotation("Create Configurations"),
	mcp.WithDescription("Creates or updates a configuration for a specific component, provided either as environment variables or as a mounted file within the component's running pod.\n\nSENSITIVE VALUES: do NOT pass secrets (passwords, API keys, tokens, connection strings with credentials) through this tool. Values sent here travel through the conversation and may be retained in logs or transcripts. Instead, tell the user to set them in the web console, on the integration's overview page via the Configure form, where secret values are write-only. Use this tool for non-sensitive configuration, and for the non-sensitive keys of a mixed configuration.\n\nCHOOSING mount_type — this depends on the integration's buildpack, and getting it wrong means the runtime never reads the values:\n- WSO2 Integrator on its default Ballerina profile (buildpack 'ballerina'; displayType starts with 'ballerina'): use mount_type 'file mount'. This runtime reads configurable values from Config.toml, so keys passed as environment variables are not picked up. Set file_mount_content to the Config.toml body (TOML 'key = value' lines) and file_mount_path to exactly '/config/Config.toml'.\n- WSO2 Integrator on the Micro Integrator (MI) profile (buildpack 'microintegrator'; displayType starts with 'mi'): use mount_type 'env variable' and pass env_variables. That profile takes its configuration from environment variables, not Config.toml.\n\nIf mount_type is 'env variable', you must provide env_variables as a JSON array of key-value pairs (e.g., [{\"key\": \"DB_HOST\", \"value\": \"localhost\"}]). If mount_type is 'file mount', you must provide file_mount_content (the file body) and file_mount_path (the full path including filename inside the pod).\n\nThe component must already be deployed before configurations can be applied."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(true),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("integration_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the component to apply the configuration to."),
	),
	mcp.WithString("project_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the project containing the component."),
	),
	mcp.WithString("environment_id",
		mcp.Required(),
		mcp.Description("The ID of the specific environment (e.g., Development, Production) where this configuration will be applied."),
	),
	mcp.WithString("component_deployment_track_id",
		mcp.Required(),
		mcp.Description("The ID of the component's deployment track where this configuration will be applied."),
	),
	mcp.WithString("configuration_name",
		mcp.Required(),
		mcp.Description("A unique name for this configuration (e.g., DATABASE_CREDS, APPLICATION_SETTINGS_FILE)."),
	),
	mcp.WithString("configuration_type",
		mcp.Required(),
		mcp.Description("Specifies the sensitivity of the configuration. Use 'config-map' for non-sensitive data. Prefer NOT to create 'secret' values through this tool — direct the user to the web console's Configure form instead, so the value never passes through the conversation. Valid values: 'config-map', 'secret'."),
		mcp.Enum(
			"config-map",
			"secret",
		),
	),
	mcp.WithString("mount_type",
		mcp.Required(),
		mcp.Description("How the configuration should be made available to the component's pod. Valid values: 'file mount', 'env variable'."),
		mcp.Enum(
			"file mount",
			"env variable",
		),
	),
	mcp.WithString("environment_template_id",
		mcp.Required(),
		mcp.Description("The ID of the environment template corresponding to the project environment."),
	),
	mcp.WithString("env_variables",
		mcp.Description("JSON array of environment variables to set, as key-value pairs. Optional. This is required if mount_type is 'env variable'. Key name='key' and value name='value'. For example, [{\"key\": \"DB_HOST\", \"value\": \"localhost\"}, {\"key\": \"DB_PORT\", \"value\": \"5432\"}]"),
	),
	mcp.WithString("file_mount_path",
		mcp.Description("The full file system path (including filename) where the configuration file should be mounted. Required if mount_type is 'file mount'. For a WSO2 Integrator integration on the default Ballerina profile this must be exactly '/config/Config.toml'."),
	),
	mcp.WithString("file_mount_content",
		mcp.Description("The content to be written into the mounted file. Required if mount_type is 'file mount'."),
	),
)
