package execution

import "github.com/mark3labs/mcp-go/mcp"

var GetExecutionsTool = mcp.NewTool("get_executions",
	mcp.WithTitleAnnotation("Get Executions"),
	mcp.WithDescription("Lists past runs and their outcomes for a deployed integration in a given environment. APPLIES ONLY TO THE 'Automation' SUBTYPE (a scheduled/cron task). Executions do not exist for 'API', 'AI Agent', 'MCP Server' (request-driven services) or 'Event Integration' / 'File Integration' (event handlers) — calling this on any of those returns an error, it does not return an empty list. Note that 'Automation' is a specific subtype, not an umbrella for anything that runs unattended: an Event Integration also runs without manual intervention but has no executions. Use get_integrations to check the integration's type first if unsure."),
	mcp.WithReadOnlyHintAnnotation(true),
	mcp.WithDestructiveHintAnnotation(false),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("integration_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the component to get execution details from."),
	),
	mcp.WithString("project_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the project containing the component."),
	),
	mcp.WithString("environment_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the environment where the component is deployed."),
	),
)

var ExecuteTaskTool = mcp.NewTool("execute_task",
	mcp.WithTitleAnnotation("Execute Task"),
	mcp.WithDescription("Triggers a deployed integration to run once, on demand, in a specific environment. APPLIES ONLY TO THE 'Automation' SUBTYPE (a scheduled/cron task), which this runs immediately instead of waiting for its next scheduled slot. Not valid for 'API', 'AI Agent', 'MCP Server' (invoke their HTTP endpoint instead) or 'Event Integration' / 'File Integration' (they run when their event or file trigger fires; there is no way to trigger them manually) — calling this on any of those returns an error. Note that 'Automation' is a specific subtype, not an umbrella for anything that runs unattended. Use get_integrations to check the integration's type first if unsure."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(true),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("integration_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the task component to execute."),
	),
	mcp.WithString("project_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the project containing the task component."),
	),
	mcp.WithString("environment_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the environment where the task component is deployed."),
	),
	mcp.WithString("runtime_arguments",
		mcp.Description("A comma-separated list of arguments to pass to the task at runtime."),
	),
)
