package deployment

import "github.com/mark3labs/mcp-go/mcp"

var GetDeploymentTool = mcp.NewTool("get_deployment",
	mcp.WithTitleAnnotation("Get Deployment"),
	mcp.WithDescription("Retrieves the current deployment details for a specific component in a given environment. This includes information about the build deployed, its status (ACTIVE, INACTIVE, FAILED), and the invoke URL (if applicable)."),
	mcp.WithReadOnlyHintAnnotation(true),
	mcp.WithDestructiveHintAnnotation(false),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("integration_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the component to get deployment details from."),
	),
	mcp.WithString("project_uuid",
		mcp.Required(), mcp.Description("The UUID of the project containing the component."),
	),
	mcp.WithString("environment_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the environment (e.g., Development, Production) where the component is deployed."),
	),
)

var CreateDeploymentTool = mcp.NewTool("create_deployment",
	mcp.WithTitleAnnotation("Create Deployment"),
	mcp.WithDescription("Deploys a new version of a component to a specified environment. This action makes a built artifact (image or build reference) active and accessible in that environment."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(false),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("integration_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the component to deploy."),
	),
	mcp.WithString("project_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the project containing the component."),
	),
	mcp.WithString("component_deployment_track_id",
		mcp.Required(),
		mcp.Description("The ID of the component's deployment track (e.g., Development, Production)."),
	),
	mcp.WithString("build_ref_or_image_id",
		mcp.Required(),
		mcp.Description("The identifier of the build to deploy. For all component types (services, webapps, scheduled tasks) except API-Proxy, this is the image ID from the build info. For API-Proxy components, this is the buildRef attribute from the build info."),
	),
	mcp.WithString("build_run_id",
		mcp.Description("The ID of the build run to deploy. This is the runId attribute from the build info."),
		mcp.Required(),
	),
	mcp.WithString("cron_expression",
		mcp.Description("The cron expression to create a scheduled task deployment for. Required only for scheduled task components."),
	),
	mcp.WithString("cron_timezone",
		mcp.Description("The cron timezone to create a scheduled task deployment for. Required only for scheduled task components."),
	),
	mcp.WithString("environment_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the environment to deploy to."),
	),
)
