package integration

import (
	"github.com/mark3labs/mcp-go/mcp"
	"github.com/wso2/integration-platform-tools/internal/mcp/utils"
)

var GetIntegrationsTool = mcp.NewTool("get_integrations",
	mcp.WithTitleAnnotation("Get Integrations"),
	mcp.WithDescription("Retrieves a list of all integrations within a specified project. If an integration_uuid is provided, it will return a list containing only that specific integration. This tool provides high-level details about each integration. Invoke this tool before calling any other integration-related tools."),
	mcp.WithReadOnlyHintAnnotation(true),
	mcp.WithDestructiveHintAnnotation(false),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("project_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the project to retrieve integrations from."),
	),
	mcp.WithString("integration_uuid",
		mcp.Description("The UUID of a specific integration to retrieve details for."),
	),
)

var CreateIntegrationTool = mcp.NewTool("create_integration",
	mcp.WithTitleAnnotation("Create Integration"),
	mcp.WithDescription("Deploys a WSO2 Integrator project (Ballerina profile or Micro Integrator/MI profile) to the WSO2 Integration Platform cloud. This is the tool to use when the user asks to 'deploy to cloud', 'push to cloud', or 'host' their integration. The source code must already be pushed to a GitHub repository before calling this. The `subtype` determines the integration kind: 'Automation' (scheduled task), 'API' (HTTP service), 'AI Agent' (LLM-backed service), 'MCP Server' (Model Context Protocol), 'Event Integration' (event-driven), 'File Integration' (file-triggered). By default the integration is automatically built and deployed after creation.\n\nONE INTEGRATION PER PROJECT PER SOURCE: this tool refuses to create a second integration in a project when one with the same name, or backed by the same repository+branch+subpath, is already there. To ship new code to an existing integration use `create_build` then `create_deployment` instead — it is already wired to the repository. To deploy the same source into a DIFFERENT project, call this again with that project's `project_uuid` (from `get_projects`); the same repository may back integrations in several projects. Different subpaths of one monorepo are distinct integrations and are allowed in the same project. If unsure whether it already exists, call `get_integrations` for the project first."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(true),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("project_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the project to create the integration in."),
	),
	mcp.WithString("name",
		mcp.Required(),
		mcp.Pattern(utils.ValidComponentNameRegex),
		mcp.Description("The name of the integration to create."),
	),
	mcp.WithString("description",
		mcp.Description("A brief description of the integration."),
	),
	mcp.WithString("subtype",
		mcp.Required(),
		mcp.Description("The kind of integration to create. These six values are a FLAT, MUTUALLY EXCLUSIVE set — there is no hierarchy and no subtype-of relationship between them. In particular 'Automation' does NOT mean 'anything that runs unattended'; it specifically means a scheduled (cron) task, and an Event Integration is a separate subtype, not a kind of Automation. "+
			"Choose by TRIGGER: a clock or schedule -> 'Automation'; an inbound HTTP request -> 'API'; an inbound HTTP request to an LLM-backed service -> 'AI Agent'; an MCP client request -> 'MCP Server'; an external event or queue/topic message -> 'Event Integration'; a file arriving or changing -> 'File Integration'. "+
			"Capability differences follow from this: only 'Automation' supports executions (get_executions, execute_task); only 'API', 'AI Agent' and 'MCP Server' have HTTP endpoints and therefore test keys, custom domains and URL mappings. "+
			"If the trigger is unclear from the user's wording, ask rather than guessing. Call get_started for the full taxonomy and capability matrix."),
		mcp.Enum(Subtypes...),
	),
	mcp.WithString("repository_url",
		mcp.Required(),
		mcp.Description("The Git repository URL of the integration's codebase. Must end with .git."),
		mcp.Pattern(utils.ValidGitUrlRegex),
	),
	mcp.WithString("branch",
		mcp.Description("The branch of the repository to build from. OPTIONAL — omit it unless you already know the branch for certain. When omitted, the tool tries '"+DefaultBranch+"' and then falls back to '"+FallbackBranch+"', which covers essentially every freshly published GitHub repository. Do NOT ask the user to run 'git branch --show-current' to find it: the cloud editor has no terminal. Only pass this when the branch is genuinely something else (e.g. 'develop')."),
	),
	mcp.WithString("subpath",
		mcp.Description("The relative subpath within the repository where the integration's source code is located. Defaults to the repository root."),
		mcp.DefaultString(""),
	),
	mcp.WithString("buildpack",
		mcp.Description("The WSO2 Integrator runtime profile to use. 'ballerina' maps to the WSO2 Integrator default profile. Use 'microintegrator' only when the user explicitly asks for Micro Integrator / MI / wso2mi."),
		mcp.Enum("ballerina", "microintegrator"),
		mcp.DefaultString("ballerina"),
	),
	mcp.WithBoolean("auto_build",
		mcp.Description("Automatically trigger a build right after the integration is created."),
		mcp.DefaultBool(true),
	),
	mcp.WithBoolean("auto_deploy",
		mcp.Description("Automatically deploy the integration once it builds successfully. Always set to true. If the integration has mandatory configurables, the user configures them via the 'Configure' button on the environment card in the integration overview page at https://console.devant.dev."),
		mcp.DefaultBool(true),
	),
)
