package database

import "github.com/mark3labs/mcp-go/mcp"

var CreateDatabaseServerTool = mcp.NewTool("create_database_server",
	mcp.WithTitleAnnotation("Create Database Server"),
	mcp.WithDescription("Provisions a new database instance. You can specify the database type, cloud provider, region, and desired service plan based on your requirements. The name must be unique within the organization and follow specific naming conventions (alphanumeric, start with a letter, max 64 chars). NOTE: Creating a new database can take a significant amount of time. If your current task depends on a new database, it is recommended to perform the database creation in an earlier step to avoid delays."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(true),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("database_type",
		mcp.Required(),
		mcp.Description("The type of database to create. Supported values: 'MySQL', 'Postgres', 'Choreo Cache'."),
		mcp.Enum("mysql", "postgres", "choreo-cache"),
	),
	mcp.WithString("name",
		mcp.Required(),
		mcp.Description("A unique name for the database instance within your organization."),
		mcp.Pattern("^[a-zA-Z][a-zA-Z0-9-]{0,63}$"),
	),
	mcp.WithString("cloud_provider",
		mcp.Required(),
		mcp.Description("The cloud provider where the database will be hosted. Supported values: 'digitalocean', 'aws', 'azure', 'gcp'."),
		mcp.Enum("digitalocean", "aws", "azure", "gcp"),
	),
	mcp.WithString("region",
		mcp.Required(),
		mcp.Description("The geographic region for the database instance. Supported values: 'us', 'eu', 'aus'."),
		mcp.Enum("us", "eu", "aus"),
	),
	mcp.WithString("service_plan",
		mcp.Required(),
		mcp.Description("The service plan to use for the database instance, determining its resources and cost. Supported values vary by provider, but commonly include: 'hobbyist', 'startup 4', 'business 4', 'business 16', 'premium 4', 'premium 8'."),
		mcp.Enum("hobbyist", "startup 4", "business 4", "business 16", "premium 4", "premium 8"),
	),
)

var GetDatabaseServerTool = mcp.NewTool("get_database_server",
	mcp.WithTitleAnnotation("Get Database Server"),
	mcp.WithDescription("Retrieves the detailed information for a specific database instance that you have already provisioned. This includes its status, connection parameters, and other relevant information. Use this when you have the UUID of a single database server and need its specific details."),
	mcp.WithReadOnlyHintAnnotation(true),
	mcp.WithDestructiveHintAnnotation(false),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("database_server_uuid",
		mcp.Description("The UUID of the database server to retrieve."),
	),
	mcp.WithString("database_server_name",
		mcp.Description("The name of the database server to retrieve. This is optional and can be used to filter the results by name."),
	),
)

var PublishDefaultDatabaseTool = mcp.NewTool("publish_default_database",
	mcp.WithTitleAnnotation("Publish Default Database"),
	mcp.WithDescription("Publishes the default database of a specified database server to the Marketplace, making it discoverable and consumable by other integrations. PRE-CONDITION: The relevant database server must be in an ACTIVE state. Use the get_database_server tool to check its current status."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(true),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("database_server_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the database server whose default database is to be published."),
	),
)
