package customDomain

import "github.com/mark3labs/mcp-go/mcp"

var RegisterCustomDomainTool = mcp.NewTool("register_custom_domain",
	mcp.WithTitleAnnotation("Register Custom Domain"),
	mcp.WithDescription("Register a custom domain within your organization for a specific integration type and environment. This is an organization-level action; afterwards use create_url_mapping to point the domain at a particular integration.\n\nAPPLIES ONLY TO INTEGRATIONS THAT EXPOSE AN HTTP ENDPOINT: the 'API', 'AI Agent' and 'MCP Server' subtypes, all of which are registered under the single component_type value 'api'. Custom domains are meaningless for 'Automation' (a scheduled task) and 'Event Integration' / 'File Integration' (event handlers), since none of them serve HTTP traffic. A domain can be registered for only one environment and integration-type combination."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(true),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("domain_name",
		mcp.Required(),
		mcp.Description("The fully qualified domain name to register (e.g., 'api.example.com'). Do not include protocols (http://, https://) or paths."),
	),
	mcp.WithString("component_type",
		mcp.Required(),
		mcp.Description("The type of integration this domain will be associated with. Supported value: 'api' (for API, AI Agent, or MCP Server integrations)."),
		mcp.Enum("api"),
	),
	mcp.WithString("env_template_id",
		mcp.Required(),
		mcp.Description("The template ID of the environment where this domain will be registered. Retrieve this using the get_project_environments tool. Production environment is recommended if no specific environment is required."),
	),
	mcp.WithString("tls_provider",
		mcp.Required(),
		mcp.Description("The TLS certificate provider. Options: 'lets_encrypt' (certificates are automatically provisioned) or 'custom' (you provide your own certificates). Use 'lets_encrypt' if the user doesn't specifically ask for custom certificates."),
		mcp.Enum("lets_encrypt", "custom"),
	),
)

var GetCustomDomainsTool = mcp.NewTool("get_custom_domains",
	mcp.WithTitleAnnotation("Get Custom Domains"),
	mcp.WithDescription("Retrieve all custom domains registered in your organization. Results include domain names, their associated integration type (always 'api', which covers the 'API', 'AI Agent' and 'MCP Server' subtypes) and the template ids of the environments they are configured for. Read-only and organization-wide; it does not require an integration."),
	mcp.WithReadOnlyHintAnnotation(true),
	mcp.WithDestructiveHintAnnotation(false),
	mcp.WithIdempotentHintAnnotation(true),
	mcp.WithOpenWorldHintAnnotation(true),
)

var CreateUrlMappingTool = mcp.NewTool("create_url_mapping",
	mcp.WithTitleAnnotation("Create URL Mapping"),
	mcp.WithDescription("Map a registered custom domain to a specific integration, so it can be reached through that domain. The domain must already be registered with register_custom_domain for the same environment and integration type.\n\nAPPLIES ONLY TO INTEGRATIONS THAT EXPOSE AN HTTP ENDPOINT: the 'API', 'AI Agent' and 'MCP Server' subtypes, all mapped under the single component_type value 'api'. There is nothing to map for 'Automation' (a scheduled task) or 'Event Integration' / 'File Integration' (event handlers), as they do not serve HTTP traffic."),
	mcp.WithReadOnlyHintAnnotation(false),
	mcp.WithDestructiveHintAnnotation(true),
	mcp.WithIdempotentHintAnnotation(false),
	mcp.WithOpenWorldHintAnnotation(true),
	mcp.WithString("domain_id",
		mcp.Required(),
		mcp.Description("The ID of the registered custom domain to use for this mapping. Retrieve this using the get_custom_domains tool."),
	),
	mcp.WithString("environment_uuid",
		mcp.Required(),
		mcp.Description("The ID of the environment where the custom domain is registered."),
	),
	mcp.WithString("project_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the project containing the component to map."),
	),
	mcp.WithString("integration_uuid",
		mcp.Required(),
		mcp.Description("The UUID of the component to map to this custom domain."),
	),
	mcp.WithString("component_type",
		mcp.Required(),
		mcp.Description("The type of integration being mapped. Supported value: 'api' (API, AI Agent, or MCP Server)."),
		mcp.Enum("api"),
	),
	mcp.WithString("api_id",
		mcp.Required(),
		mcp.Description("The integration's API ID. Use get_deployments to find the latest apimId."),
	),
	mcp.WithString("default_domain",
		mcp.Required(),
		mcp.Description("The component's current default domain name without any path. Retrieve this from the get_deployments tool, ensuring it's from the same environment where the custom domain is registered."),
	),
	mcp.WithString("default_path",
		mcp.Description("The path portion of the API's default URL (only for 'api' component type). Extract this from the deployment URL using the get_deployments tool."),
	),

	mcp.WithString("custom_path",
		mcp.Description("The new URL path where the API will be accessible within the custom domain (only for 'api' component type). Use only if the user specifically requires a custom path."),
	),
)
